#!/usr/bin/env bash
# ============================================================================
# 本地 git 钩子层自检：断言"文档 / 配置里声称已生效的本地防线"**确实已安装**
#
# 【为什么需要它】
#   （2026-09-18 实测事故：devlog 0014 §3/§5、一致性报告 A-11 / 新增 A-15）
#   本仓库的文档与配置长期声称"本地 pre-commit 提供密钥扫描（detect-private-key）
#   与提交信息校验（commitizen）"，而 `.git/hooks/` 实质**长期为空**——钩子从未安装。
#   原因：`make setup` 用 `CI` 环境变量的**存在性**推断"要不要装钩子"，
#   而本工作区恰好带着 `CI=true`（"云开发环境"被当成了"CI 流水线"）。
#   后果：**声称的保护与真正运行的保护之间是空的**，且长期无人察觉——
#   因为没有任何检查会因"钩子不存在"而失败。
#   ⇒ 凡"声称已生效的缓解措施"，必须能被**实测**。本脚本就是这条断言的载体。
#
# 【它断言什么】（任何一条不满足即失败，fail-secure）
#   1. `.git/hooks/<hook>` 存在；
#   2. 可执行（git 只执行可执行文件；不可执行 = 静默不生效）；
#   3. 是 **pre-commit 生成的**（含其模板标记），而不是被别的脚本顶替；
#   4. 指向本仓库的 `.pre-commit-config.yaml`（换成别的配置 = 跑的不是声明的规则）；
#   5. 钩子类型与文件名一致（`--hook-type=<hook>`），防止"钩子装串了"
#      （把 commit-msg 的内容装到 pre-commit 上，两道校验就只剩一道）。
#
# 【用法】
#   check-local-hooks.sh [--hook <名称>]...
#     默认检查：pre-commit、commit-msg（即 `.pre-commit-config.yaml` 的
#     `default_install_hook_types`）。
#
# 【退出码】
#   0  全部通过
#   1  钩子缺失 / 不可执行 / 不是 pre-commit 生成 / 指向别的配置（fail-secure）
#   2  用法错误，或当前目录不是 git 仓库
#
# 【与 make 的分工（有意为之）】
#   本脚本**只做断言、不做策略**：它不判断"这里该不该有钩子"。
#   "CI 流水线不需要本地钩子"由调用方**显式**表达（`make ... LOCAL_HOOKS=0`），
#   脚本本身**没有** "跳过" 开关——静默跳过正是它要消灭的失效模式。
# ============================================================================

set -euo pipefail

readonly DEFAULT_HOOKS=("pre-commit" "commit-msg")
readonly GENERATED_MARKER="File generated by pre-commit"
readonly CONFIG_BASENAME=".pre-commit-config.yaml"

HOOKS=()
FAILURES=0

log() { printf '[local-hooks] %s\n' "$*"; }
fail() { printf '[local-hooks][FAIL] %s\n' "$*" >&2; }
die() {
    printf '[local-hooks][ERROR] %s\n' "$*" >&2
    exit 2
}

usage() {
    cat <<'USAGE'
用法：check-local-hooks.sh [--hook <名称>]...

  --hook <名称>   要检查的钩子名（可重复；默认 pre-commit 与 commit-msg）
  -h, --help      显示本帮助
USAGE
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        --hook)
            [[ $# -ge 2 ]] || die "--hook 缺少取值"
            HOOKS+=("$2")
            shift 2
            ;;
        -h | --help)
            usage
            exit 0
            ;;
        *) die "未知参数：$1" ;;
    esac
done
[[ ${#HOOKS[@]} -gt 0 ]] || HOOKS=("${DEFAULT_HOOKS[@]}")

git rev-parse --git-dir >/dev/null 2>&1 || die "当前目录不是 git 仓库"

for hook in "${HOOKS[@]}"; do
    hook_path="$(git rev-parse --git-path "hooks/${hook}")"

    if [[ ! -e "${hook_path}" ]]; then
        fail "${hook}：钩子不存在（${hook_path}）"
        FAILURES=$((FAILURES + 1))
        continue
    fi

    if [[ ! -x "${hook_path}" ]]; then
        fail "${hook}：钩子存在但不可执行（${hook_path}）—— git 不会执行它，等于没装"
        FAILURES=$((FAILURES + 1))
        continue
    fi

    content="$(cat "${hook_path}")"

    if [[ "${content}" != *"${GENERATED_MARKER}"* ]]; then
        fail "${hook}：不是 pre-commit 生成的钩子（缺少标记「${GENERATED_MARKER}」）—— 可能被别的脚本顶替"
        FAILURES=$((FAILURES + 1))
        continue
    fi

    if [[ "${content}" != *"${CONFIG_BASENAME}"* ]]; then
        fail "${hook}：未指向本仓库的 ${CONFIG_BASENAME} —— 跑的不是声明的规则"
        FAILURES=$((FAILURES + 1))
        continue
    fi

    if [[ "${content}" != *"--hook-type=${hook}"* ]]; then
        fail "${hook}：钩子类型不匹配（未声明 --hook-type=${hook}）—— 钩子装串了，该跑的校验没跑"
        FAILURES=$((FAILURES + 1))
        continue
    fi

    log "${hook}：OK（${hook_path}）"
done

if [[ "${FAILURES}" -gt 0 ]]; then
    fail "共 ${FAILURES} 项不满足：**本地防线当前并未生效**（检查通过 ≠ 保护生效）。"
    fail "修复：执行 \`make setup\`（安装钩子后本脚本会立即复验）。"
    exit 1
fi

log "✅ 本地钩子层已实测生效（${HOOKS[*]}）"
exit 0
