"""本地门禁的「可实测性」：声称已生效的缓解措施必须能被检查验穿。

背景（2026-09-18 实测事故，一致性报告 **A-11 / 新增 A-15**、devlog 0014 §3/§5）：
本仓库的文档与配置长期声称"本地 pre-commit 提供密钥扫描（`detect-private-key`）与
提交信息校验（commitizen）"，而 `.git/hooks/` 实质**长期为空**——钩子从未安装。
根因是 `make setup` 用 `$CI` 环境的**存在性**推断"要不要装钩子"，而云开发工作区
恰好带着 `CI=true`。于是"声称的保护"与"真正运行的保护"之间是空的，
**且没有任何检查会因"钩子不存在"而失败**，问题因此活了很久才被发现。

教训（0014 §6 第二条）：凡"缺失应失败"的约束，必须把"缺失"这个状态本身做成失败条件。
本文件把"声称"变成两组可执行断言：

1. **声明层**：`.pre-commit-config.yaml` 确实声明了那两道防线，且声明要装的钩子类型
   与 `scripts/check-local-hooks.sh` 断言的类型一致；
2. **安装层**：`scripts/check-local-hooks.sh` 在钩子缺失 / 不可执行 / 被顶替 /
   指向别的配置 / 钩子装串了时**必须非零退出**——用临时 git 仓库真实复现这五种状态，
   证明这道检查不是"永远返回 0 的装饰"。
"""

from __future__ import annotations

import pathlib
import subprocess

import pytest

REPO_ROOT = pathlib.Path(__file__).resolve().parents[2]
PRE_COMMIT_CONFIG = REPO_ROOT / ".pre-commit-config.yaml"
MAKEFILE = REPO_ROOT / "Makefile"
HOOKS_SCRIPT = REPO_ROOT / "scripts" / "check-local-hooks.sh"

#: 与 pre-commit 生成的钩子模板一致的最小内容（标记行取自实际安装后的 `.git/hooks/*`）
PRE_COMMIT_HOOK_MARKER = "# File generated by pre-commit: https://pre-commit.com"


# ---------------------------------------------------------------------------
# 1. 声明层：配置里确实声明了这两道本地防线
# ---------------------------------------------------------------------------


@pytest.mark.unit
def test_pre_commit_config_declares_the_claimed_local_defences() -> None:
    """A-11 声称的"本地密钥扫描 + 提交信息校验"必须在配置里真的存在。

    只断言"钩子文件在"是不够的：钩子是通用壳子，真正决定跑什么的是这份配置。
    把配置里的这两条删掉，钩子依然存在、依然通过存在性检查，保护却没了。
    """
    text = PRE_COMMIT_CONFIG.read_text(encoding="utf-8")

    assert "- id: detect-private-key" in text, "本地密钥扫描（detect-private-key）已不在配置中"
    assert "- id: commitizen" in text, "提交信息校验（commitizen）已不在配置中"
    assert "stages: [commit-msg]" in text, "commitizen 必须挂在 commit-msg 阶段才生效"


@pytest.mark.unit
def test_declared_hook_types_match_what_the_check_asserts() -> None:
    """`default_install_hook_types` 与检查脚本断言的钩子集合必须一致。

    否则会出现"配置声明要装 3 个钩子、检查只断言 2 个"的缺口——
    恰好又是"检查通过 ≠ 保护生效"。
    """
    text = PRE_COMMIT_CONFIG.read_text(encoding="utf-8")
    declared = next(
        line for line in text.splitlines() if line.startswith("default_install_hook_types:")
    )
    assert declared.strip() == "default_install_hook_types: [pre-commit, commit-msg]"

    script = HOOKS_SCRIPT.read_text(encoding="utf-8")
    assert 'DEFAULT_HOOKS=("pre-commit" "commit-msg")' in script


# ---------------------------------------------------------------------------
# 2. 安装层：检查脚本在五种"看起来装了"的情况下都必须报红
# ---------------------------------------------------------------------------


def _init_repo(tmp_path: pathlib.Path) -> pathlib.Path:
    repo = tmp_path / "repo"
    repo.mkdir()
    subprocess.run(["git", "init", "-q", str(repo)], check=True, capture_output=True)
    return repo


def _write_hook(
    repo: pathlib.Path,
    name: str,
    *,
    hook_type: str | None = None,
    config: str = ".pre-commit-config.yaml",
    body: str | None = None,
    executable: bool = True,
) -> pathlib.Path:
    path = repo / ".git" / "hooks" / name
    if body is None:
        body = "\n".join(
            [
                "#!/usr/bin/env bash",
                PRE_COMMIT_HOOK_MARKER,
                f"ARGS=(hook-impl --config={config} --hook-type={hook_type or name})",
                "",
            ]
        )
    path.write_text(body, encoding="utf-8")
    path.chmod(0o755 if executable else 0o644)
    return path


def _run_hook_check(repo: pathlib.Path) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        ["bash", str(HOOKS_SCRIPT)],
        cwd=repo,
        capture_output=True,
        text=True,
        check=False,
    )


def _install_both_hooks(repo: pathlib.Path) -> None:
    _write_hook(repo, "pre-commit")
    _write_hook(repo, "commit-msg")


@pytest.mark.unit
def test_installed_hooks_pass(tmp_path: pathlib.Path) -> None:
    """正常安装的两道钩子应当通过（否则这道检查本身不可用）。"""
    repo = _init_repo(tmp_path)
    _install_both_hooks(repo)

    result = _run_hook_check(repo)

    assert result.returncode == 0, result.stderr
    assert "pre-commit：OK" in result.stdout
    assert "commit-msg：OK" in result.stdout


@pytest.mark.unit
def test_missing_hooks_fail_secure(tmp_path: pathlib.Path) -> None:
    """钩子不存在（A-15 的真实情形）必须非零退出——这正是原先没人发现的那个状态。"""
    repo = _init_repo(tmp_path)

    result = _run_hook_check(repo)

    assert result.returncode == 1, "钩子缺失却返回 0：检查形同虚设"
    assert "钩子不存在" in result.stderr
    assert "make setup" in result.stderr, "失败信息必须给出可执行的修复命令"


@pytest.mark.unit
def test_non_executable_hook_fails(tmp_path: pathlib.Path) -> None:
    """不可执行的钩子 git 不会运行它——存在但没生效，必须判失败。"""
    repo = _init_repo(tmp_path)
    _install_both_hooks(repo)
    _write_hook(repo, "commit-msg", executable=False)

    result = _run_hook_check(repo)

    assert result.returncode == 1
    assert "不可执行" in result.stderr


@pytest.mark.unit
def test_foreign_hook_fails(tmp_path: pathlib.Path) -> None:
    """被别的脚本顶替的钩子不算数：它跑的不是声明的规则。"""
    repo = _init_repo(tmp_path)
    _install_both_hooks(repo)
    _write_hook(repo, "pre-commit", body="#!/usr/bin/env bash\nexit 0\n")

    result = _run_hook_check(repo)

    assert result.returncode == 1
    assert "不是 pre-commit 生成的钩子" in result.stderr


@pytest.mark.unit
def test_hook_pointing_to_another_config_fails(tmp_path: pathlib.Path) -> None:
    """钩子指向别的配置文件 = 跑的不是本仓库声明的规则。"""
    repo = _init_repo(tmp_path)
    _install_both_hooks(repo)
    _write_hook(repo, "pre-commit", config=".pre-commit-config-other.yaml")

    result = _run_hook_check(repo)

    assert result.returncode == 1
    assert ".pre-commit-config.yaml" in result.stderr


@pytest.mark.unit
def test_hook_type_mismatch_fails(tmp_path: pathlib.Path) -> None:
    """钩子装串了（commit-msg 位置上装着 pre-commit 的钩子）必须被发现。"""
    repo = _init_repo(tmp_path)
    _write_hook(repo, "pre-commit")
    _write_hook(repo, "commit-msg", hook_type="pre-commit")

    result = _run_hook_check(repo)

    assert result.returncode == 1
    assert "钩子类型不匹配" in result.stderr


@pytest.mark.unit
def test_outside_a_git_repository_is_a_usage_error(tmp_path: pathlib.Path) -> None:
    """不在 git 仓库里是用法错误（rc=2），不是"通过"。"""
    result = _run_hook_check(tmp_path)

    assert result.returncode == 2
    assert "不是 git 仓库" in result.stderr


# ---------------------------------------------------------------------------
# 3. 接线：根因修掉了，且两道新门禁真的挂在聚合目标上
# ---------------------------------------------------------------------------


@pytest.mark.unit
def test_hook_install_is_no_longer_inferred_from_ci_env_var() -> None:
    """根因回归守卫：不得再用 `$CI` 推断"要不要装钩子"。

    云开发工作区与 CI 流水线在该变量上可能取同一个值，语义却相反
    （本工作区实测 `CI` 未设置，而更早的工作区 `CI=true` 只是云环境）。
    显式开关是 `LOCAL_HOOKS`。
    """
    text = MAKEFILE.read_text(encoding="utf-8")

    assert "$$CI" not in text, "钩子安装又变回了按 $CI 推断（A-15 的根因）"
    assert "LOCAL_HOOKS ?= 1" in text, "默认应安装钩子（只有 CI 显式关闭）"


@pytest.mark.unit
def test_make_check_covers_local_hooks_and_secret_scan() -> None:
    """`make check` 必须覆盖本地钩子层与密钥扫描——否则"声称的防线"又只在纸面上。"""
    text = MAKEFILE.read_text(encoding="utf-8")
    check_target = next(line for line in text.splitlines() if line.startswith("check:"))
    security_target = next(line for line in text.splitlines() if line.startswith("security:"))

    assert "hooks-check" in check_target, "make check 未覆盖本地钩子层"
    assert "security-secrets" in security_target, "密钥扫描未纳入 security 聚合"
